name: Main

on:
  push:
    tags: "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: demopkg-${{ matrix.os }}
          path: |
            target/release/demopkg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download bins
        uses: actions/download-artifact@v4

      - name: Extract changelog
        run: |
          awk '/^# / { if (version_block) { exit } version_block = 1 } version_block' CHANGELOG.md > gh_changelog
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: demopkg-windows-latest, demopkg-ubuntu-latest, demopkg-macos-latest
          body_path: gh_changelog
